### ISSUE TITLE
Запускается, но ничего не происходит

### ISSUE THREAD

**Issue by dreadushka** [kottofey/VizinerCypher#1]
C:\Users\Ilya\Downloads>VizinerCipher-1.0.exe
Viziner Cipher: This application requires a Java Runtime Environment.

Может нужно какие-то ключи или еще что-то. Может к приложению help написать, чтобы его можно было вызвать привычным способом через --help. Или он сам бы выводил помощь, если заданы неправильные или недостаточные параметры.

ОС:
Выпуск	Windows 11 Pro
Версия	22H2
Дата установки	‎29.‎12.‎2022
Сборка ОС	22621.963
Взаимодействие	Windows Feature Experience Pack 1000.22638.1000.0

**Comment by kottofey** [comment]
Привет! Я поправил README, там описание способов как запустить. Exe файл запускается, если джава установлена в стандартное место. Иначе надо запускать через терминал `java -jar ...`

**Comment by kottofey** [comment]
Починил в релизе 2.0-RC

https://github.com/kottofey/VizinerCypher/releases/tag/v2.0-RC
